
title: something
author: other
email: theagent@thesocietyofxtras.com
description: > # this means to ignore newlines until "baseurl:"
  not sure whats going on.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
