--
title:hooves
date:2019-03-13
--


title: Horror title
author: Devil
email: burn@inhell.com
description: > # this means to ignore newlines until "baseurl:"
Hot Hot Hot 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
